services:
  mongodb:
    image: mongo:latest
    command: --quiet --logpath /dev/null
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

  backend:
    build:
      context: .
      target: hot-reload
    command: '-build="sleep 3 && go build -o /build/main main.go" -command="/build/main" -log-prefix=false'
    ports:
      - "8000:8000"
    volumes:
      - ./:/app:ro
    depends_on:
      - mongodb

volumes:
  mongodb-data:
