services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

volumes:
  mongodb-data:
