services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis

volumes:
  redis-data:
